
services:

    dbal.user.repository:
        alias: App\Repository\DBALUserRepository
        public: true

    no_directory.tile.repository:
        class: App\Repository\TextMapTileRepository
        public: true
        arguments: [
            '%kernel.project_dir%/tests/Data/storage/invalid/map',
            '%map.width%',
            '%map.chunk%',
        ]

    no_file.tile.repository:
        class: App\Repository\TextMapTileRepository
        public: true
        arguments: [
            '%kernel.project_dir%/tests/Data/storage/invalid',
            '%map.width%',
            '%map.chunk%',
        ]

    empty_file.tile.repository:
        class: App\Repository\TextMapTileRepository
        public: true
        arguments: [
            '%kernel.project_dir%/tests/Data/storage/empty',
            '%map.width%',
            '%map.chunk%',
        ]

    App\Repository\TextMapTileRepository:
        public: true
        arguments: [
            '%kernel.project_dir%/tests/Data/storage/map',
            '%map.width%',
            '%map.chunk%',
        ]