OpenTribes\Core\Entity\Building:
    type: entity
    table: ot_buildings
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        slot:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        level:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        status:
            type: BuildStatus
            nullable: false
            length: 0
            options:
                fixed: false
                default: default
        locationX:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: location_x
        locationY:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: location_y
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
